-- MySQL Script generated by MySQL Workbench
-- Thu May 29 15:33:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema codelocker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema codelocker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codelocker` DEFAULT CHARACTER SET utf8 ;
USE `codelocker` ;

-- -----------------------------------------------------
-- Table `codelocker`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codelocker`.`tipo` (
  `tipo_id` INT NOT NULL,
  `tipo_nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`tipo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codelocker`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codelocker`.`usuarios` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_nome` VARCHAR(100) NOT NULL,
  `usuario_email` VARCHAR(100) NOT NULL,
  `usuario_telefone` VARCHAR(100) NOT NULL,
  `usuario_senha` VARCHAR(100) NOT NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`usuario_id`),
  INDEX `tipo_id_idx` (`tipo` ASC) VISIBLE,
  CONSTRAINT `tipo_id`
    FOREIGN KEY (`tipo`)
    REFERENCES `codelocker`.`tipo` (`tipo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codelocker`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codelocker`.`status` (
  `id_status` INT NOT NULL,
  `status_nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codelocker`.`salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codelocker`.`salas` (
  `sala_id` INT NOT NULL AUTO_INCREMENT,
  `sala_nome` VARCHAR(100) NOT NULL,
  `id_usuario` INT NOT NULL,
  `status_sala` INT NOT NULL,
  PRIMARY KEY (`sala_id`),
  INDEX `usuario_id_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `id_status_idx` (`status_sala` ASC) VISIBLE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `codelocker`.`usuarios` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_status`
    FOREIGN KEY (`status_sala`)
    REFERENCES `codelocker`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codelocker`.`log_salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codelocker`.`log_salas` (
  `log_id` INT NOT NULL,
  `id_sala` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `data` VARCHAR(100) NOT NULL,
  `hora` VARCHAR(100) NOT NULL,
  `status` INT NOT NULL,
  `observacao` VARCHAR(200) NULL,
  PRIMARY KEY (`log_id`),
  INDEX `sala_id_idx` (`id_sala` ASC) VISIBLE,
  INDEX `usuario_id_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `id_status_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `sala_id`
    FOREIGN KEY (`id_sala`)
    REFERENCES `codelocker`.`salas` (`sala_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `codelocker`.`usuarios` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_status`
    FOREIGN KEY (`status`)
    REFERENCES `codelocker`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
