-- MySQL Script generated by MySQL Workbench
-- Thu Jun  5 15:04:09 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lockerdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lockerdb` ;

-- -----------------------------------------------------
-- Schema lockerdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lockerdb` DEFAULT CHARACTER SET utf8 ;
USE `lockerdb` ;

-- -----------------------------------------------------
-- Table `lockerdb`.`reg_salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lockerdb`.`reg_salas` (
  `id` INT NOT NULL,
  `id_salas` INT NOT NULL,
  `data` VARCHAR(100) NOT NULL,
  `usuario_id` INT NOT NULL,
  `observacao` VARCHAR(200) NULL,
  `reg_status` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`id_salas` ASC) VISIBLE,
  INDEX `id_idx1` (`usuario_id` ASC) VISIBLE,
  INDEX `id_reg_status_idx` (`reg_status` ASC) VISIBLE,
  CONSTRAINT `id_salas`
    FOREIGN KEY (`id_salas`)
    REFERENCES `lockerdb`.`salas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `lockerdb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_reg_status`
    FOREIGN KEY (`reg_status`)
    REFERENCES `lockerdb`.`reg_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lockerdb`.`reg_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lockerdb`.`reg_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reg_status` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lockerdb`.`salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lockerdb`.`salas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `id_ususario` INT NULL,
  `status_sala` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`id_ususario` ASC) VISIBLE,
  INDEX `id_idx1` (`status_sala` ASC) VISIBLE,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_ususario`)
    REFERENCES `lockerdb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_status`
    FOREIGN KEY (`status_sala`)
    REFERENCES `lockerdb`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lockerdb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lockerdb`.`status` (
  `id` INT NOT NULL,
  `status` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lockerdb`.`tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lockerdb`.`tipos` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lockerdb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lockerdb`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `qrcode` VARCHAR(100) NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`tipo` ASC) VISIBLE,
  CONSTRAINT `id_tipo`
    FOREIGN KEY (`tipo`)
    REFERENCES `lockerdb`.`tipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
